### PR TITLE
Updated readme.md

### PR DESCRIPTION
**Pull request by ChrisCates**
Added installation instructions for maven and gradle.

### CODE REVIEW

**Comment by matthewbahr** [comment]
Jitpack is not functional for me. It cannot resolve dependency.

**Comment by bcersows** [comment]
Not working for me either.
Always throwing an error that the POM cannot be read because of missing authentication.

Anyone knows a fix?

**Comment by matthewbahr** [comment]
I grabbed the repo and manually added it to my project. 

Good luck.

**Comment by bcersows** [comment]
Hey @matthewbahr (and all others),

lazy as I am I forked this project (https://github.com/bcersows/java-client) and made it maven-ready.  
Instructions in the README.

Cheers! 🍺

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/SignalR/java-client/blob/master/readme.md.

**Pull request closed without merging**
