### PR TITLE
Adding SSL feature to WebSocketTransport

### PR DESCRIPTION
**Pull request by Kasraaa**
setCertificateForWebsocket method will use for configuring wss communications later.

### CODE REVIEW

**Comment by hongnguyenpro** [comment]
Why WebSocket do not work with branch master. When the working final version release? Please help me! Thanks!

**Comment by Kasraaa** [comment]
@hongnguyenpro are you sure that enabled websocket feature on your server?

**Comment by hongnguyenpro** [comment]
@Kasraaa How can i enabled websocket feature on my server? And proxy network will drop package of websocket? Thanks so much!

**Comment by Kasraaa** [comment]
@hongnguyenpro look at this link:
http://www.iis.net/configreference/system.webserver/websocket

**Comment by hongnguyenpro** [comment]
Finally, I used long-polling because of some reasons of server. BTW, Thank you very much!

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/SignalR/java-client/blob/master/readme.md.

**Pull request closed without merging**
